# Generated by Django 6.0.2 on 2026-03-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='e.g. MP, FBC, URS', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference_range', models.TextField(blank=True, help_text='Normal reference range text')),
                ('unit', models.CharField(blank=True, help_text='e.g. cells/μL, mg/dL', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Routine', 'Routine'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Routine', max_length=10)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical history / notes for the lab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, help_text='Leave blank for walk-in request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='consultations.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_requests', to='patients.patient')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Lab scientist who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_processed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField(blank=True, help_text='Free-form result text')),
                ('reference_range', models.CharField(blank=True, help_text='Copied from catalog, editable per result', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('interpretation', models.CharField(blank=True, choices=[('', '— Not set —'), ('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Critical', 'Critical')], max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks / comments')),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labrequest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['test__name'],
                'unique_together': {('request', 'test')},
            },
        ),
    ]
