# Generated by Django 6.0.2 on 2026-03-05 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(editable=False, help_text='Auto-generated e.g. CON-2024-00001', max_length=30, unique=True)),
                ('bp_systolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('bp_diastolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=5, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('extra_vitals', models.JSONField(blank=True, default=dict)),
                ('chief_complaint', models.TextField(blank=True, help_text="Patient's main complaint")),
                ('history', models.TextField(blank=True, help_text='History of presenting illness')),
                ('examination', models.TextField(blank=True, help_text='Physical examination findings')),
                ('diagnosis', models.TextField(blank=True, help_text="Doctor's diagnosis (free text)")),
                ('icd10_code', models.CharField(blank=True, help_text='Optional ICD-10 code e.g. J06.9', max_length=20)),
                ('icd10_label', models.CharField(blank=True, help_text='ICD-10 description', max_length=255)),
                ('management_plan', models.TextField(blank=True, help_text='Treatment and management plan')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('has_prescription', models.BooleanField(default=False)),
                ('has_lab_request', models.BooleanField(default=False)),
                ('has_ward_referral', models.BooleanField(default=False)),
                ('has_clearance', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, help_text='Leave blank for walk-in consultations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consultations', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_at'],
            },
        ),
    ]
