# Generated by Django 6.0.2 on 2026-03-06 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='e.g. Bed 1, B-01', max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='e.g. Near window, isolation bed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('reason', models.TextField(help_text='Reason for admission / diagnosis')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Transferred', 'Transferred'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitting_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='consultations.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_discharged', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.bed')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='wards.ward')),
            ],
            options={
                'ordering': ['-admitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='wards.admission')),
                ('from_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='wards.bed')),
                ('to_bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='wards.bed')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_done', to=settings.AUTH_USER_MODEL)),
                ('from_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='wards.ward')),
                ('to_ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='wards.ward')),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
