# Generated by Django 6.0.2 on 2026-03-07 22:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('doc_type', models.CharField(choices=[('sick_leave', 'Sick Leave Letter'), ('fit_to_resume', 'Medical Certificate (Fit to Resume)'), ('referral', 'Referral Letter'), ('medical_report', 'Medical Report / Summary')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('revoked', 'Revoked')], default='draft', max_length=10)),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_to', models.DateField(blank=True, null=True)),
                ('resume_date', models.DateField(blank=True, null=True)),
                ('referral_to', models.CharField(blank=True, max_length=200)),
                ('referral_department', models.CharField(blank=True, max_length=200)),
                ('referral_reason', models.TextField(blank=True)),
                ('referral_urgency', models.CharField(blank=True, choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], max_length=10)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('verification_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_documents', to='consultations.consultation')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_issued', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_documents', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
