# Generated by Django 6.0.2 on 2026-03-06 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('inventory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='General prescription notes')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Dispensed', 'Dispensed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, help_text='Leave blank for walk-in / independent prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='Auto-filled from inventory or typed manually', max_length=200)),
                ('dosage', models.CharField(blank=True, help_text='e.g. 500mg, 2 tablets', max_length=100)),
                ('frequency', models.CharField(blank=True, choices=[('Once daily', 'Once daily (OD)'), ('Twice daily', 'Twice daily (BD)'), ('Three times daily', 'Three times daily (TDS)'), ('Four times daily', 'Four times daily (QDS)'), ('Every 4 hours', 'Every 4 hours'), ('Every 6 hours', 'Every 6 hours'), ('Every 8 hours', 'Every 8 hours'), ('At night', 'At night (nocte)'), ('As needed', 'As needed (PRN)'), ('Stat', 'Immediately (Stat)'), ('Other', 'Other')], max_length=50)),
                ('duration', models.CharField(blank=True, help_text='e.g. 7 days, 2 weeks', max_length=100)),
                ('route', models.CharField(choices=[('Oral', 'Oral'), ('IV', 'Intravenous (IV)'), ('IM', 'Intramuscular (IM)'), ('SC', 'Subcutaneous (SC)'), ('Topical', 'Topical'), ('Sublingual', 'Sublingual'), ('Inhaled', 'Inhaled'), ('Rectal', 'Rectal'), ('Ophthalmic', 'Ophthalmic (Eye)'), ('Otic', 'Otic (Ear)'), ('Nasal', 'Nasal'), ('Other', 'Other')], default='Oral', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity to dispense')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions e.g. take with food')),
                ('dispensed_qty', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='inventory.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
