# Generated by Django 6.0.2 on 2026-03-07 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(help_text='e.g. 2024/2025', max_length=20)),
                ('stream', models.CharField(choices=[('I', 'Stream I'), ('II', 'Stream II')], max_length=5)),
                ('title', models.CharField(blank=True, help_text='Optional display title e.g. "2024/2025 Stream I Medical Clearance"', max_length=200)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_sessions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_session', 'stream'],
                'unique_together': {('academic_session', 'stream')},
            },
        ),
        migrations.CreateModel(
            name='ClearanceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='text', max_length=20)),
                ('choices_json', models.TextField(blank=True, default='[]')),
                ('is_required', models.BooleanField(default=False)),
                ('field_key', models.CharField(blank=True, choices=[('', '— None —'), ('blood_group', 'Blood Group'), ('genotype', 'Genotype'), ('known_allergies', 'Known Allergies'), ('chronic_conditions', 'Chronic Conditions'), ('disabilities', 'Disabilities'), ('blood_pressure', 'Blood Pressure')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='clearance.clearancesession')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ClearanceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20)),
                ('resubmit_granted', models.BooleanField(default=False)),
                ('resubmit_granted_at', models.DateTimeField(blank=True, null=True)),
                ('extended_deadline', models.DateTimeField(blank=True, help_text='If set, student can submit until this date even if session is closed', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearance_submissions', to='patients.patient')),
                ('resubmit_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmit_grants', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_reviewed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='clearance.clearancesession')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('session', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='ClearanceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clearance.clearancequestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clearance.clearancesubmission')),
            ],
            options={
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
