# Generated by Django 6.0.2 on 2026-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('single', 'Single Choice'), ('multiple', 'Multiple Choice')], default='text', max_length=20)),
                ('choices_json', models.TextField(blank=True, default='[]')),
                ('is_required', models.BooleanField(default=False)),
                ('field_key', models.CharField(blank=True, choices=[('', '— None —'), ('blood_group', 'Blood Group'), ('genotype', 'Genotype'), ('known_allergies', 'Known Allergies'), ('chronic_conditions', 'Chronic Conditions'), ('disabilities', 'Disabilities'), ('blood_pressure', 'Blood Pressure')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
