# Generated by Django 6.0.2 on 2026-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_defaultquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancequestion',
            name='is_preloaded',
            field=models.BooleanField(default=False, help_text='Copied from default template — edit via Default Questions page only.'),
        ),
    ]
