# Generated by Django 6.0.2 on 2026-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0004_clearancequestion_is_preloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancesession',
            name='academic_session',
            field=models.CharField(help_text='e.g. 2024/2025', max_length=25),
        ),
    ]
