# Generated by Django 6.0.2 on 2026-03-04 12:04

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='patients.faculty')),
            ],
            options={
                'ordering': ['faculty__name', 'name'],
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('duration', models.PositiveSmallIntegerField(default=5, help_text='Programme duration in years (e.g. 4, 5, 6)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='patients.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='patients.faculty')),
            ],
            options={
                'ordering': ['faculty__name', 'name'],
                'unique_together': {('faculty', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(help_text="This is the patient's unique identifier.", max_length=30, unique=True, verbose_name='Matric / Student ID')),
                ('patient_type', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Dependant', 'Dependant'), ('External', 'External / Walk-in')], default='Student', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=patients.models.patient_photo_path)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=15)),
                ('religion', models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional'), ('Other', 'Other'), ('None', 'None / Prefer not to say')], max_length=20)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100, verbose_name='LGA of Origin')),
                ('home_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nin', models.CharField(blank=True, max_length=20, verbose_name='National ID (NIN)')),
                ('level', models.CharField(blank=True, choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('Postgraduate', 'Postgraduate')], max_length=20)),
                ('academic_session', models.CharField(blank=True, help_text='e.g. 2023/2024', max_length=20, verbose_name='Entry Session')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='One allergy per line')),
                ('chronic_conditions', models.TextField(blank=True, help_text='One condition per line')),
                ('disabilities', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('surgical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_address', models.TextField(blank=True)),
                ('nok_name', models.CharField(blank=True, max_length=200, verbose_name='Next of Kin Name')),
                ('nok_relationship', models.CharField(blank=True, max_length=100, verbose_name='Relationship')),
                ('nok_phone', models.CharField(blank=True, max_length=20, verbose_name='Next of Kin Phone')),
                ('nok_address', models.TextField(blank=True, verbose_name='Next of Kin Address')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes visible to clinic staff only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('sync_source', models.CharField(blank=True, default='MANUAL', help_text='MANUAL | CSV_IMPORT | NEU_PORTAL', max_length=50)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.faculty')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='patients.programme', verbose_name='Programme of Study')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
